Update the system requirements in the README.md
contao/managed-edition pull request #32
Opened 2018-01-17 10:50 UTC by netzarbeiter

Die Frage zur Systemanforderung von Contao taucht immer wieder auf, in einem nächsten Schritt könnten wir diese Informationen im Download-Bereich direkt zur Verfügung stellen.
contao/website#100

Kannst du bitte noch die MariaDB-Version angeben.

2018-01-17 13:22 UTC, leofeyer commented
Wofür brauchen wir `proc_open` und `proc_close` in Contao?

2018-01-17 13:28 UTC, fritzmg commented
@netzarbeiter `proc_open` und `proc_close` sind für den Contao Manager, nicht für Contao selbst.

2018-01-17 13:31 UTC, netzarbeiter commented
Direkt brauchen tut es Contao nicht, aber sobald das Install-Tool (cache löschen) oder der Contao Manager ein Kommando ausführen will. Natürlich ist das nicht eine Anforderung von Contao, dann müssten wir aber konsequenterweise den Contao Manager und den Weg über die ZIP nicht ermöglichen und nur die Bedienung über die Kommandozeile anbieten.

2018-01-17 13:44 UTC, netzarbeiter commented
Das Ziel ist, dass die Leute beim Start wissen, was Contao und die Hilfswerkzeuge (Contao Manager) für Servervoraussetzungen benötigen.
Sonst sehen sie die Systemanforderungen von Contao, bereiten ihren Server vor, laden den Manager hoch und müssen auch für diesen noch Anpassungen am Server vornehmen. Fällt in meinen Augen auf Contao zurück, auch wenn der «Manager» schuld ist.

2018-01-17 14:24 UTC, fritzmg commented
> Direkt brauchen tut es Contao nicht, aber sobald das Install-Tool (cache löschen)

Stimmt. @leofeyer core-bundle verwendet Symfony\Component\Process\Process und das wiederum benötigt proc_open. Wobei ich selbst mit deaktivierten `proc_open` Funktion die Datenbank im Install Tool korrekt einrichten konnte.

2018-01-17 15:42 UTC, leofeyer commented
> Das Ziel ist, dass die Leute beim Start wissen, was Contao und die Hilfswerkzeuge (Contao Manager) für Servervoraussetzungen benötigen.

Niemand liest die README. Wenn wir Glück haben lesen die Leute die Doku und die beste Chance, gelesen zu werden, dürfte der Text auf der Webseite haben (siehe contao/website#100). 

Aber ja, wir können auch das README etwas ausführlicher machen.

2018-04-09 06:08 UTC, aschempp commented
Ich würde *Contao requires:* noch entfernen, denn das dupliziert sich ja mit dem Titel (*System Requirements*).

@contao/developers benötigen wir nicht auch die Intl-Bibliothek bereits in 4.4? Ansonsten sollten wir das vorerst mal übernehmen, wir können es jederzeit ergänzen falls noch was dazu kommt. Besser als das bestehende ist es allemal!

2018-04-09 07:30 UTC, Toflar commented
Ich würde das auch übernehmen und `intl` brauchen wir seit 4.0.

2020-05-08 08:18 UTC, leofeyer requested changes

2020-05-08 08:18 UTC, leofeyer commented on README.md
> +    * proc_close
Contao does not need `proc_open` and `proc_close`. Only the Contao Manager does (see https://github.com/contao/contao-manager/pull/554).

2020-05-08 08:21 UTC, leofeyer commented
> Direkt brauchen tut es Contao nicht, aber sobald das Install-Tool (cache löschen)

Wie beim gestrigen Mumble-Call besprochen, braucht Contao 4 `proc_open` nicht. Auch nicht, um im Install-Tool den Cache zu löschen oder in der Systemwartung die Symlinks zu regenerieren. `proc_open` ist ausschließlich für den Contao Manager notwendig, weil dieser quasi die Kommandozeile ersetzt.

2020-09-07 11:58 UTC, aschempp commented
> `proc_open` ist ausschließlich für den Contao Manager notwendig, weil dieser quasi die Kommandozeile ersetzt.

Das stimmt so nicht. Jede Nutzung von `symfony/process` braucht `proc_open`. Also
 - Der Composer ScriptHandler in der Managed Edition
 - Das ResizeImagesCommand wenn `--concurrent` benutzt wird
 - Die DotEnv Komponente, wenn Commands in der .env enthalten sind

Aber ja, für eine "normale" Ausführung benötigt Contao keine Prozesse…

2022-01-06 15:53 UTC, closed without merging